environment:

    matrix:
        # Pre-installed Python versions, which Appveyor may upgrade to
        # a later point release.
        # See: http://www.appveyor.com/docs/installed-software#python

        - PYTHON: "C:\\Python33"
          PYTHON_VERSION: "3.3.x" 
          PYTHON_ARCH: "32"

        - PYTHON: "C:\\Python33-x64"
          PYTHON_VERSION: "3.3.x"
          PYTHON_ARCH: "64"

        - PYTHON: "C:\\Python34"
          PYTHON_VERSION: "3.4.x"
          PYTHON_ARCH: "32"

        - PYTHON: "C:\\Python34-x64"
          PYTHON_VERSION: "3.4.x"
          PYTHON_ARCH: "64"

install:
    # Install Python (from the official .msi of http://python.org) and pip when
    # not already installed.
    - ps: if (-not(Test-Path($env:PYTHON))) { & appveyor\install.ps1 }

    # Prepend newly installed Python to the PATH of this build (this cannot be
    # done from inside the powershell script as it would require to restart
    # the parent CMD process).
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

    # Check that we have the expected version and architecture for Python
    - "python --version"
    - "python -c \"import struct; print(struct.calcsize('P') * 8)\"" 

build: off

test_script:
  # Run the project tests
  - "%CMD_IN_ENV% python bin/fades -r requirements.txt -x nosetests -v -s tests"
