dist: bionic

language: python

python:
      - "3.6"
      - "3.7"
      - "3.8"
      - "3.8-dev"  # 3.8 development branch
install:
    - "pip install -r requirements.txt"
    - >
      if [[ $TRAVIS_PYTHON_VERSION == '3.8' ]]
        then
          pip install python-coveralls "pytest-cov<2.6.0"
      fi
-script:
    - >
      if [[ $TRAVIS_PYTHON_VERSION == '3.8' ]]
        then
          pytest --cov=fades
        else
          pytest
      fi

# report coverage to coveralls.io
after_success:
    - >
      if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]
        then 
          coveralls
      fi

cache:
  apt: true
  pip: true
