language: python

python:
      - "3.3"
      - "3.4"
      - "3.5"
      - "3.5-dev"
      - "3.6"
      - "3.6-dev"
      - "nightly" # currently points to 3.7-dev
install:
    - "pip install -r requirements.txt"
    - "pip install python-coveralls"
script:
    - "nosetests --with-xcoverage --cover-package=fades -v fades tests"
after_script:
    - "flake8 fades --max-line-length=99 --select=E,W,F,C,N"

# report coverage to coveralls.io
after_success:
    - coveralls

cache:
  apt: true
  pip: true
